# Tells move_group how to hand trajectories to ros2_control.
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - "3rd joint bend"
      - "m3"
      - "diff-assembly-pulley"
      - "nema23"
      - "bevel gear"
      - "biomed lock mech"
